title: Portfolio
#url: "faaip.github.io"
baseurl: "/portfolio"
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/faaip"
footer_text: "Portfolio for Frederik T. Juutilainen"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Main"
   link: "index"
 - name: "Contact"
   link: "contact"
